### ISSUE TITLE
Please set your RAVE_SECRET_KEY environment variable.

### ISSUE THREAD

**Issue by PetrJoe** [remiljw/Wallet-API#1]
raise ValueError("Please set your RAVE_SECRET_KEY environment variable. Otherwise, pass publicKey and secretKey as arguments and set usingEnv to false")
ValueError: Please set your RAVE_SECRET_KEY environment variable. Otherwise, pass publicKey and secretKey as arguments and set usingEnv to false

**Comment by remiljw** [comment]
Closing this issue, you should be the one to set your own rave key, not me. Sign up on the provider to get that.

**Comment by PetrJoe** [comment]
Ok no problem


I'll find solution to that



Thinking that it is my API key that's not well configured because I am
working on adding some feature
